// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGvs3uIjnHY_mYRn6gLGkhOwwZOiJHdO4',
    appId: '1:224942158128:web:57f0739af6d41d60db18f5',
    messagingSenderId: '224942158128',
    projectId: 'ecoquest-f22e4',
    authDomain: 'ecoquest-f22e4.firebaseapp.com',
    storageBucket: 'ecoquest-f22e4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpRK410BHZpiJ2duq6vnajh-60ypoNKC4',
    appId: '1:224942158128:android:844d1d43d5ef088adb18f5',
    messagingSenderId: '224942158128',
    projectId: 'ecoquest-f22e4',
    storageBucket: 'ecoquest-f22e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnweIjUOt7UlIQ9Ga8r9VnZKsyVLcC5Is',
    appId: '1:224942158128:ios:e1a50c454a5cf6fcdb18f5',
    messagingSenderId: '224942158128',
    projectId: 'ecoquest-f22e4',
    storageBucket: 'ecoquest-f22e4.firebasestorage.app',
    iosBundleId: 'com.example.ecoquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnweIjUOt7UlIQ9Ga8r9VnZKsyVLcC5Is',
    appId: '1:224942158128:ios:e1a50c454a5cf6fcdb18f5',
    messagingSenderId: '224942158128',
    projectId: 'ecoquest-f22e4',
    storageBucket: 'ecoquest-f22e4.firebasestorage.app',
    iosBundleId: 'com.example.ecoquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGvs3uIjnHY_mYRn6gLGkhOwwZOiJHdO4',
    appId: '1:224942158128:web:c966c4dd951cf603db18f5',
    messagingSenderId: '224942158128',
    projectId: 'ecoquest-f22e4',
    authDomain: 'ecoquest-f22e4.firebaseapp.com',
    storageBucket: 'ecoquest-f22e4.firebasestorage.app',
  );
}
